pull_request_rules:
  - name: Automatic merge when all status checks pass
    conditions:
      - author~=^(snyk-bot|dependabot\[bot\])$
      - status-success=security/snyk (Bifravst)
      - status-success=tests
    actions:
      merge:
        method: rebase
        rebase_fallback: squash
        bot_account: bifravst-ci
      label:
        add:
         - mergify
      rebase:
        bot_account: bifravst-ci
