name: Test and Release

on: push

env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

jobs:
  tests:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-node@v1
        with:
          node-version: "12.x"
      - name: Install latest npm
        run: |
          sudo npm install -g npm@
          npm config set update-notifier false
          sudo chown -R $USER:$(id -gn $USER) /home/runner/.config
      - name: Authenticate with NPM
        run: |
          echo "//npm.pkg.github.com/:_authToken=$GITHUB_TOKEN" > ~/.npmrc
      - name: Install dependencies
        run: npm ci --no-audit
      - name: Compile
        run: npx tsc
      - name: Test
        run: npm test
      - name: Semantic release
        continue-on-error: true
        run: |
          npm i --no-save semantic-release@next
          npx semantic-release
